project: "li9"
auth_url: "https://172.21.81.150"
keynames:
    macbook: "dima-macbook"
flavors:
  n1_small: "n1.small"
images:
  centos7_x64: "d962e522-48be-4383-a134-ec7d064598bd"
networks:
  int1:
    id: "22f8a733-8822-4fb9-89bf-cdeaf1ef9c73"

