

- name: Create an instance in the OpenStack cloud
  os_server:
    state: present
    verify: false
    auth:
      auth_url: "{{ os_namespace.auth_url }}"
      username: "{{ os_username }}"
      password: "{{ os_password }}"
      project_name: "{{ os_namespace.project_name }}"
      domain_name: "{{ os_user_domain_name }}"
    name: "{{ vm_name }}"
    image: "{{ os_namespace.images.centos7_x64 }}"
    key_name: "{{ os_namespace.keynames.macbook }}"
    timeout: 200
    flavor: "{{ os_namespace.flavors.n1_small }}"
    nics:
      - net-id: "{{ os_namespace.networks.int1.id }}"
    meta:
      hostname: "{{ vm_name }}.{{ vm_hostname|default('') }}"
    userdata: "{{ userdata.postinstall }}"
  tags:
    - install


- name: Make the OpenStack instance not existing
  os_server:
    state: absent
    auth:
      auth_url: "{{ os_namespace.auth_url }}"
      username: "{{ os_username }}"
      password: "{{ os_password }}"
      project_name: "{{ os_namespace.project_name }}"
      domain_name: "{{ os_user_domain_name }}"
    name: "{{ vm_name }}"
    verify: false
  tags:
    - uninstall

